# Generated by Django 3.1.3 on 2020-12-05 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_date', models.DateTimeField(blank=True, null=True)),
                ('call_outcome', models.CharField(blank=True, max_length=200, null=True)),
                ('wrap_up_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('service_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReqService',
            fields=[
                ('req_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clientcontact')),
                ('service_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='ContactSession',
            fields=[
                ('contact_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_start_time', models.TimeField(blank=True, null=True)),
                ('wrap_up_duration', models.TimeField(blank=True, null=True)),
                ('call_end_time', models.TimeField(blank=True, null=True)),
                ('call_type', models.IntegerField(blank=True, null=True)),
                ('dialled', models.IntegerField(blank=True, null=True)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.brand')),
            ],
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='contact_session_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contactsession'),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='')),
                ('call_lower_limit', models.IntegerField(default=0, null=True)),
                ('call_upper_limit', models.IntegerField(default=300, null=True)),
                ('brands', models.ManyToManyField(to='accounts.Brand')),
                ('depts', models.ManyToManyField(to='accounts.Department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
