# Generated by Django 3.1.3 on 2020-12-10 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201210_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='brand_id',
        ),
        migrations.AddField(
            model_name='team',
            name='department_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
