# Generated by Django 3.1.3 on 2020-12-11 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201210_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='call_lower_limit',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='call_upper_limit',
        ),
        migrations.CreateModel(
            name='AgentSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_lower_limit', models.IntegerField(default=0, null=True)),
                ('call_upper_limit', models.IntegerField(default=300, null=True)),
                ('agent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.agent')),
                ('brands', models.ManyToManyField(to='accounts.Brand')),
                ('teams', models.ManyToManyField(to='accounts.Team')),
            ],
        ),
    ]
