# Generated by Django 3.1.3 on 2020-12-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201211_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsearch',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.agent'),
        ),
    ]
