# Generated by Django 3.1.3 on 2020-12-12 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201211_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsearch',
            name='call_lower_limit',
        ),
        migrations.RemoveField(
            model_name='agentsearch',
            name='call_upper_limit',
        ),
    ]
