# Generated by Django 3.1.3 on 2020-12-12 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201212_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsearch',
            name='call_lower_limit',
            field=models.TimeField(default=datetime.time(0, 0, 0, 22268), null=True),
        ),
        migrations.AddField(
            model_name='agentsearch',
            name='call_upper_limit',
            field=models.TimeField(default=datetime.time(0, 5, 0, 22268), null=True),
        ),
    ]
