# Generated by Django 3.1.3 on 2020-12-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201212_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentsearch',
            name='call_lower_limit',
        ),
        migrations.RemoveField(
            model_name='agentsearch',
            name='call_upper_limit',
        ),
    ]
